version: '3'
services:
    player:
        build: player/.
    user:
        build: user/.
    playlist:
        build: playlist/.
    client:
        build: client/.
        ports:
            - "3000:5000"
    nginx:
        image: nginx
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
